name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Fetch from upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/mannaandpoem/OpenManus.git
          git remote -v

      - name: Fetch all from upstream
        run: |
          git fetch upstream main:upstream-main
          git fetch upstream chat-visualization:upstream-chat-visualization
